/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as MapRouteImport } from './routes/map'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as GiftIdeasRouteImport } from './routes/gift-ideas'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DevUnlockRouteImport } from './routes/dev-unlock'
import { Route as BucketListRouteImport } from './routes/bucket-list'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurpriseIndexRouteImport } from './routes/surprise.index'
import { Route as MemoryLaneIndexRouteImport } from './routes/memory-lane.index'
import { Route as SurpriseUpsellRouteImport } from './routes/surprise.upsell'
import { Route as SurpriseQuizRouteImport } from './routes/surprise.quiz'
import { Route as SurprisePlanRouteImport } from './routes/surprise.plan'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthRecoverAccessRouteImport } from './routes/auth.recover-access'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicSyncpayWebhookRouteImport } from './routes/api/public/syncpay-webhook'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftIdeasRoute = GiftIdeasRouteImport.update({
  id: '/gift-ideas',
  path: '/gift-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUnlockRoute = DevUnlockRouteImport.update({
  id: '/dev-unlock',
  path: '/dev-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketListRoute = BucketListRouteImport.update({
  id: '/bucket-list',
  path: '/bucket-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseIndexRoute = SurpriseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurpriseRoute,
} as any)
const MemoryLaneIndexRoute = MemoryLaneIndexRouteImport.update({
  id: '/memory-lane/',
  path: '/memory-lane/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseUpsellRoute = SurpriseUpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => SurpriseRoute,
} as any)
const SurpriseQuizRoute = SurpriseQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => SurpriseRoute,
} as any)
const SurprisePlanRoute = SurprisePlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => SurpriseRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverAccessRoute = AuthRecoverAccessRouteImport.update({
  id: '/auth/recover-access',
  path: '/auth/recover-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncpayWebhookRoute = ApiPublicSyncpayWebhookRouteImport.update({
  id: '/api/public/syncpay-webhook',
  path: '/api/public/syncpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bucket-list': typeof BucketListRoute
  '/dev-unlock': typeof DevUnlockRoute
  '/gallery': typeof GalleryRoute
  '/gift-ideas': typeof GiftIdeasRoute
  '/letters': typeof LettersRoute
  '/map': typeof MapRoute
  '/milestones': typeof MilestonesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/surprise': typeof SurpriseRouteWithChildren
  '/termos': typeof TermosRoute
  '/timeline': typeof TimelineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-access': typeof AuthRecoverAccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/surprise/plan': typeof SurprisePlanRoute
  '/surprise/quiz': typeof SurpriseQuizRoute
  '/surprise/upsell': typeof SurpriseUpsellRoute
  '/memory-lane/': typeof MemoryLaneIndexRoute
  '/surprise/': typeof SurpriseIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bucket-list': typeof BucketListRoute
  '/dev-unlock': typeof DevUnlockRoute
  '/gallery': typeof GalleryRoute
  '/gift-ideas': typeof GiftIdeasRoute
  '/letters': typeof LettersRoute
  '/map': typeof MapRoute
  '/milestones': typeof MilestonesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/termos': typeof TermosRoute
  '/timeline': typeof TimelineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-access': typeof AuthRecoverAccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/surprise/plan': typeof SurprisePlanRoute
  '/surprise/quiz': typeof SurpriseQuizRoute
  '/surprise/upsell': typeof SurpriseUpsellRoute
  '/memory-lane': typeof MemoryLaneIndexRoute
  '/surprise': typeof SurpriseIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bucket-list': typeof BucketListRoute
  '/dev-unlock': typeof DevUnlockRoute
  '/gallery': typeof GalleryRoute
  '/gift-ideas': typeof GiftIdeasRoute
  '/letters': typeof LettersRoute
  '/map': typeof MapRoute
  '/milestones': typeof MilestonesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/surprise': typeof SurpriseRouteWithChildren
  '/termos': typeof TermosRoute
  '/timeline': typeof TimelineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-access': typeof AuthRecoverAccessRoute
  '/auth/signup': typeof AuthSignupRoute
  '/surprise/plan': typeof SurprisePlanRoute
  '/surprise/quiz': typeof SurpriseQuizRoute
  '/surprise/upsell': typeof SurpriseUpsellRoute
  '/memory-lane/': typeof MemoryLaneIndexRoute
  '/surprise/': typeof SurpriseIndexRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/syncpay-webhook': typeof ApiPublicSyncpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bucket-list'
    | '/dev-unlock'
    | '/gallery'
    | '/gift-ideas'
    | '/letters'
    | '/map'
    | '/milestones'
    | '/privacidade'
    | '/settings'
    | '/stats'
    | '/surprise'
    | '/termos'
    | '/timeline'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recover-access'
    | '/auth/signup'
    | '/surprise/plan'
    | '/surprise/quiz'
    | '/surprise/upsell'
    | '/memory-lane/'
    | '/surprise/'
    | '/api/public/mercadopago-webhook'
    | '/api/public/syncpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/bucket-list'
    | '/dev-unlock'
    | '/gallery'
    | '/gift-ideas'
    | '/letters'
    | '/map'
    | '/milestones'
    | '/privacidade'
    | '/settings'
    | '/stats'
    | '/termos'
    | '/timeline'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recover-access'
    | '/auth/signup'
    | '/surprise/plan'
    | '/surprise/quiz'
    | '/surprise/upsell'
    | '/memory-lane'
    | '/surprise'
    | '/api/public/mercadopago-webhook'
    | '/api/public/syncpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bucket-list'
    | '/dev-unlock'
    | '/gallery'
    | '/gift-ideas'
    | '/letters'
    | '/map'
    | '/milestones'
    | '/privacidade'
    | '/settings'
    | '/stats'
    | '/surprise'
    | '/termos'
    | '/timeline'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/recover-access'
    | '/auth/signup'
    | '/surprise/plan'
    | '/surprise/quiz'
    | '/surprise/upsell'
    | '/memory-lane/'
    | '/surprise/'
    | '/api/public/mercadopago-webhook'
    | '/api/public/syncpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BucketListRoute: typeof BucketListRoute
  DevUnlockRoute: typeof DevUnlockRoute
  GalleryRoute: typeof GalleryRoute
  GiftIdeasRoute: typeof GiftIdeasRoute
  LettersRoute: typeof LettersRoute
  MapRoute: typeof MapRoute
  MilestonesRoute: typeof MilestonesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  SurpriseRoute: typeof SurpriseRouteWithChildren
  TermosRoute: typeof TermosRoute
  TimelineRoute: typeof TimelineRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverAccessRoute: typeof AuthRecoverAccessRoute
  AuthSignupRoute: typeof AuthSignupRoute
  MemoryLaneIndexRoute: typeof MemoryLaneIndexRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicSyncpayWebhookRoute: typeof ApiPublicSyncpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-ideas': {
      id: '/gift-ideas'
      path: '/gift-ideas'
      fullPath: '/gift-ideas'
      preLoaderRoute: typeof GiftIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-unlock': {
      id: '/dev-unlock'
      path: '/dev-unlock'
      fullPath: '/dev-unlock'
      preLoaderRoute: typeof DevUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bucket-list': {
      id: '/bucket-list'
      path: '/bucket-list'
      fullPath: '/bucket-list'
      preLoaderRoute: typeof BucketListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise/': {
      id: '/surprise/'
      path: '/'
      fullPath: '/surprise/'
      preLoaderRoute: typeof SurpriseIndexRouteImport
      parentRoute: typeof SurpriseRoute
    }
    '/memory-lane/': {
      id: '/memory-lane/'
      path: '/memory-lane'
      fullPath: '/memory-lane/'
      preLoaderRoute: typeof MemoryLaneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise/upsell': {
      id: '/surprise/upsell'
      path: '/upsell'
      fullPath: '/surprise/upsell'
      preLoaderRoute: typeof SurpriseUpsellRouteImport
      parentRoute: typeof SurpriseRoute
    }
    '/surprise/quiz': {
      id: '/surprise/quiz'
      path: '/quiz'
      fullPath: '/surprise/quiz'
      preLoaderRoute: typeof SurpriseQuizRouteImport
      parentRoute: typeof SurpriseRoute
    }
    '/surprise/plan': {
      id: '/surprise/plan'
      path: '/plan'
      fullPath: '/surprise/plan'
      preLoaderRoute: typeof SurprisePlanRouteImport
      parentRoute: typeof SurpriseRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-access': {
      id: '/auth/recover-access'
      path: '/auth/recover-access'
      fullPath: '/auth/recover-access'
      preLoaderRoute: typeof AuthRecoverAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/syncpay-webhook': {
      id: '/api/public/syncpay-webhook'
      path: '/api/public/syncpay-webhook'
      fullPath: '/api/public/syncpay-webhook'
      preLoaderRoute: typeof ApiPublicSyncpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SurpriseRouteChildren {
  SurprisePlanRoute: typeof SurprisePlanRoute
  SurpriseQuizRoute: typeof SurpriseQuizRoute
  SurpriseUpsellRoute: typeof SurpriseUpsellRoute
  SurpriseIndexRoute: typeof SurpriseIndexRoute
}

const SurpriseRouteChildren: SurpriseRouteChildren = {
  SurprisePlanRoute: SurprisePlanRoute,
  SurpriseQuizRoute: SurpriseQuizRoute,
  SurpriseUpsellRoute: SurpriseUpsellRoute,
  SurpriseIndexRoute: SurpriseIndexRoute,
}

const SurpriseRouteWithChildren = SurpriseRoute._addFileChildren(
  SurpriseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BucketListRoute: BucketListRoute,
  DevUnlockRoute: DevUnlockRoute,
  GalleryRoute: GalleryRoute,
  GiftIdeasRoute: GiftIdeasRoute,
  LettersRoute: LettersRoute,
  MapRoute: MapRoute,
  MilestonesRoute: MilestonesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  SurpriseRoute: SurpriseRouteWithChildren,
  TermosRoute: TermosRoute,
  TimelineRoute: TimelineRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverAccessRoute: AuthRecoverAccessRoute,
  AuthSignupRoute: AuthSignupRoute,
  MemoryLaneIndexRoute: MemoryLaneIndexRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicSyncpayWebhookRoute: ApiPublicSyncpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
