// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hscoblnnvlynrlyhhocm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzY29ibG5udmx5bnJseWhob2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1NDY2NTksImV4cCI6MjA5NDEyMjY1OX0.Hplr7Yn37QHHoSuo02j5QeGLzMS6VrA9k4_N49hHGJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});